name: npm build and linting
on: workflow_dispatch
jobs:
  firstjob:
    runs-on: ubuntu-22.04
    steps:
      - name: First step
        run: echo 'This is first step'
      - name: Checkout code and install
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: build your code
        run: npm run build
      - name: test your code
        run: npm run test

